package br.com.zup.edu.ligaqualidade.desafioemprestimoimobiliario.modifique.enums;

public enum PROPONENT_COLUMNS {
    EVENT_ID,EVENT_SCHEMA,EVENT_ACTION,EVENT_TIMESTAMP,PROPOSAL_ID,PROPONENT_ID,PROPONENT_NAME,PROPONENT_AGE,PROPONENT_MONTHLY_INCOME,PROPONENT_IS_MAIN
}
